Feature/set weights and bias
PetrKubes97/ts-neural-network pull request #4
Opened 2023-06-08 21:39 UTC by Wissiak

@PetrKubes97 Thanks for your review! I'm very happy that you like my proposal and I've implemented the changes you've asked for. 

The diff for index.html still is a mess but somehow if I reset the file and add the changes manually, WebStorm doesn't recognize the space / line break changes 😕

2023-06-09 13:35 UTC, PetrKubes97 requested changes

2023-06-09 13:35 UTC, PetrKubes97 commented on src/neuralNetwork/Connection.ts
> +    this.weight = weight || Math.random();
I think the weights should still be between centered around zero. Not sure why I had the * 10 - 5 before, but at least -0.5 would make sense.

2023-06-09 13:35 UTC, PetrKubes97 commented on src/neuralNetwork/NeuralCore.ts
> +  private weightList: number[][][];
Weight is saved in the neuron's connection, so this should not be necessary.

2023-06-09 13:35 UTC, PetrKubes97 commented on src/neuralNetwork/NeuralCore.ts
> +  }
This functions should loop through all the neurons and their connections and set the weights accordingly.

2023-06-09 13:35 UTC, PetrKubes97 commented on src/neuralNetwork/NeuralCore.ts
> +          const connection = new Connection(currNeuron, nextNeuron, weight)
This should be removed after the previous changes.

2023-06-09 13:37 UTC, PetrKubes97 commented
Do you think it is necessary to have the set weights in a separate variable from the actual weights (Neuron->connections)? I might be missing something, but seems more intuitive to me to just set actual weights. 

For the formatting, I'll do a reformat and add .editorconfig later today.

2023-06-09 15:12 UTC, Wissiak commented
Your observation is correct and I've adapted the code to set the weights directly on the connection.

2023-06-09 22:40 UTC, PetrKubes97 commented
I've pushed the .editorconfig file and reformatted the whole project. I'm using intellij, so the formatting should match.

2023-06-10 09:56 UTC, Wissiak commented
I have updated the pull-request now with the .editorconfig and the diff looks better now 👍

2023-06-10 14:53 UTC, PetrKubes97 commented
Ok, looks good, however I've still found a few problems.

1. Setting random weights clears the weights field to '[]' which is not consistent with the behaviour for inputs. If input changes (using the sliders), the set input field does not reset.
2. Clicking on row from training data to activate inputs stopped working.

2023-06-10 16:19 UTC, Wissiak commented
1. I've adapted the behavior to not reset the weights
2. The problem was that I've put the `draw()` call at the end of the `updateUI()` function. Since upon updating the UI, the cost is being calculated, `NeuralCore.evaluate(inputSample)` is being called for each training data input. The `NeuralCore.evaluate(inputSample)` function updates the input neurons to have the values of the given inputSample which then ended up showing only the last training data input. Upon reverting my `draw()` call reorder change, the UI is being updated to the right time again. 

In addition:
Since I din't know that I could change the input sample by clicking on a row in the table, I've added a hint to the UI.

2023-06-10 16:32 UTC, PetrKubes97 commented
Nice work! Merging now.

2023-06-10 16:32 UTC, merged